### ISSUE TITLE
Figure out how to get the DOGE sending amount consistent.

### ISSUE THREAD

**Issue by tweber22** [geo-gs/dogeyip#1]
@geo-gs I think that we should find a way to make the amount of DOGE to send to commit a message more consistent, so we won't be sending random amounts of DOGE each time someone sends a message.

My idea is to have the chat submission start out at a fixed amount of DOGE for the first post (ex. .0001 DOGE) and increase the amount of DOGE by a fixed amount (ex. .00000001 DOGE) for each post(8 decimal places is the max resolution that is widely supported). 

That way we could not be sending random amounts of DOGE around, and we could search on transaction amount on the blockchain for a natural chronological sorting. 

It would also be nice of we could make the signup fee something more round, like 15 DOGE, for ease of reading and remembering.

Let me know what you think of these ideas, or if you have any better ideas.

**Comment by geo-gs** [comment]
@tweber22 
The tricky part is that people can use these accounts for other things than just this app. I chose a small non-round numbers to reduce the likelyhood that someone actually transfer that amount to a real address. Also, to me `2093` looks a bit like `DOgE`.

I don't know that we actually need to have a counter in the transfer amount for natural chronological sorting as the block chain actually keeps a timestamp (in seconds) for every transaction committed.

However, I see your point that .2093 doge coins does seem a little random. Instead maybe we should say that a transaction is a post if the last hex value is between 8000 and 9FFF.

I think you're right about the sign up transaction amount, I'll change the index to look for 15 DOGE.

**Comment by tweber22** [comment]
@geo-gs What do you mean by "the last hex value"?

**Comment by geo-gs** [comment]
@tweber22 
So if `48656c6c6f20576f726c6421` is the hex values for `Hello World!` then the hash160 that we would use would be `48656c6c6f20576f726c64212020202020202080`.

Note that 20 in hex is whitespace and that the above hash160 ends in a hex value between 80 and 9F.

**Comment by tweber22** [comment]
@geo-gs Ok. So would we send 48656c6c6f20576f726c64212020202020202080 into the hashing algorithm?

**Comment by geo-gs** [comment]
Yup

**Comment by tweber22** [comment]
@geo-gs so we will get a fake address like 17bo9qr42A5krwASCcoDGFTq9bNtkzSxcE, and that is where we will send the DOGE?

**Comment by tweber22** [comment]
And we will look up all transactions from the sending address to get a chat history?

**Comment by geo-gs** [comment]
@tweber22 
Right now I think that is our only option. Do you know of another way?

**Comment by tweber22** [comment]
I can't think of anything else. I think that is a good option for now. What should we set the comment post cost at?

**Comment by tweber22** [comment]
The way I understand it, we are sending every comment to a different (fake) address for a constant DOGE amount. Is this correct?

**Comment by geo-gs** [comment]
Not quite. We are sending every comment to a different (fake) address. We are no longer going to care about the DOGE amount because we decode the address and look at the last hex value to determine if it is a comment.

So the posting message now reads
> Make a Dogecoin Transaction with the Below Address to Post Text.

**Comment by tweber22** [comment]
@geo-gs I see, so users can post any doge amount that they want to the given fake address. That will work.

**Comment by tweber22** [comment]
Closing.
