### ISSUE TITLE
Rework encode/decode to use dictionary

### ISSUE THREAD

**Issue by tweber22** [geo-gs/dogeyip#2]
@geo-gs are you using SHA256 to hash the text at all in the address generation process?

**Comment by geo-gs** [comment]
@tweber22 
Yup. You double sha256 the hash to get the checksum.

**Comment by tweber22** [comment]
@geo-gs how are you decoding the addresses back to text?

**Comment by geo-gs** [comment]
@tweber22 
You should be able to convert base58 to hash and then just ignore the checksum.

**Comment by geo-gs** [comment]
@tweber22 
I'm actually using a precompiled js library at the moment. Getting a human-readable javascript version of this is on the todo list.

**Comment by tweber22** [comment]
So you are converting the address from base58 to hex, and then decrypting it via RIPEMD-160 to the hex string representation of the message?

**Comment by geo-gs** [comment]
No. I guess I used the wrong terminology there. I'm doing the following:
* Convert Base58 to RIPEMD-160
* Convert RIPEMD-160 to an array of hex values
* Chopping off the first and last four hex vales from the array
* Dictionary decompressing the hex array (if applicable)
* Convert any remaining hex values to characters.

**Comment by tweber22** [comment]
where is the actual decyrpting taking place?

**Comment by geo-gs** [comment]
[Here](https://github.com/geo-gs/dogeyip/blob/gh-pages/js/doge_yip_read.js#L317) is a place where I try to decode an address to text.
[Here](https://github.com/geo-gs/dogeyip/blob/gh-pages/js/doge_yip_read.js#L1) is the base58CheckTohash160 function.
[Here](https://github.com/geo-gs/dogeyip/blob/gh-pages/js/doge_yip_hash160ToText.js#L1) is the hash160ToText function.

**Comment by tweber22** [comment]
Encoding and decoding now uses the dictionary. Closing issue.
