### ISSUE TITLE
Add User List to Main Page of App

### ISSUE THREAD

**Issue by tweber22** [geo-gs/dogeyip#3]
Add the user list to the main page of the app.  This should be a listview with clickable links to an activity page of the user clicked on.

**Comment by tweber22** [comment]
@geo-gs how are you parsing the doggechain transactions to doge-yip to get the usernames that users set?

**Comment by tweber22** [comment]
@geo-gs found it. ScrapeTransaction of read.js.

**Comment by geo-gs** [comment]
Yeah. I've updated it since then. Now Look at doge_yip_address_ajax.js

Also, yesterday I added in a php caching proxy since chain.so only keeps the last 50 transactions.

**Comment by tweber22** [comment]
@geo-gs @tweber22 Closing, as the app is no longer in development.
