### ISSUE TITLE
Add payment and donation ability to app.

### ISSUE THREAD

**Issue by tweber22** [geo-gs/dogeyip#6]
@tweber22 Add ability to post transactions to the dogechain for posting content and giving in-app donations.

**Comment by tweber22** [comment]
I think I got it to send a request to an external dogecoin app. Will install langerhans doge wallet apk to emulator to test this. Closing for now.

**Comment by geo-gs** [comment]
Cool!

**Comment by tweber22** [comment]
@geo-gs just got the langerhans dogecoin wallet installed on the emulator, and the buttons start up the wallet and initiate a transaction to the supplied address!
